name: Deploy to Koyeb
on:
  push:
    branches:
      - main

jobs:
  deploy-spring:
    runs-on: ubuntu-latest
    environment: koyeb-config
    steps:
      - uses: actions/checkout@v4
      - name: Install Koyeb CLI
        run: |
          curl -sL https://get.koyeb.com | bash
          echo "$HOME/.koyeb/bin" >> $GITHUB_PATH
      - name: Deploy Spring service
        run: |
          koyeb login --token ${{ secrets.KOYEB_API_TOKEN }}
          koyeb service redeploy reliable-melinde/assessment-project

  deploy-summarizer:
    runs-on: ubuntu-latest
    environment: koyeb-config
    steps:
      - uses: actions/checkout@v4
      - name: Install Koyeb CLI
        run: |
          curl -sL https://get.koyeb.com | bash
          echo "$HOME/.koyeb/bin" >> $GITHUB_PATH
      - name: Deploy Summarizer service
        run: |
          koyeb login --token ${{ secrets.KOYEB_API_TOKEN }}
          koyeb service redeploy daily-danni/assessment-project