name: Deploy Services To Koyeb

on:
  push:
    branches:
      - main

jobs:
  deploy-spring:
    name: Deploy Spring Backend
    runs-on: ubuntu-latest
    environment: koyeb-config
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Spring service
        run: |
          curl -sL https://get.koyeb.com | bash
          koyeb login --token ${{ secrets.KOYEB_API_TOKEN }}
          koyeb services redeploy reliable-melinde --app assessment-project

  deploy-summarizer:
    name: Deploy Summarizer Service
    runs-on: ubuntu-latest
    environment: koyeb-config
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Summarizer service
        run: |
          curl -sL https://get.koyeb.com | bash
          koyeb login --token ${{ secrets.KOYEB_API_TOKEN }}
          koyeb services redeploy daily-danni --app assessment-project
